In [3]:
a = [1, 2, 3, 4, 5] # リストの作成
print(a)

[1, 2, 3, 4, 5]


In [4]:
len(a)

5

In [5]:
a[0]

1

In [6]:
a[4]

5

In [8]:
a[4] = 99 # 値を代入
print(a)

[1, 2, 3, 4, 99]


In [9]:
print(a)

[1, 2, 3, 4, 99]


In [10]:
a[0:2]

[1, 2]

In [11]:
a[1:]

[2, 3, 4, 99]

In [12]:
a[:3]

[1, 2, 3]

In [ ]:
a[:-1] # 最初から最後の要素一つ前まで取得

[1, 2, 3, 4]

In [14]:
a[:-2] # 最初から最後の要素の2つ前まで取得

[1, 2, 3]

In [15]:
me = {"height": 100} # 辞書作成
me["height"]

100

In [16]:
me["weight"] = 70 # 新しい要素を追加
print(me)

{'height': 100, 'weight': 70}


In [17]:
hungry = True # お腹空いてる？
sleepy = False # 眠い？
type(hungry)

bool

In [18]:
not hungry

False

In [ ]:
hungry and sleepy # 空腹かつ眠い

False

In [20]:
hungry or sleepy # 空腹または眠い

True

In [21]:
def hello():
    print("Hello World!")

hello()

Hello World!


In [23]:
def hello(object):
    print("Hello" + object + "!")

hello("cat")

Hellocat!


In [24]:
import numpy as np

In [25]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [26]:
type(x)

numpy.ndarray

In [ ]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x +  y # 要素ごとの足し算

array([3., 6., 9.])

In [ ]:
x - y

array([-1., -2., -3.])

In [30]:
x * y

array([ 2.,  8., 18.])

In [31]:
x / y

array([0.5, 0.5, 0.5])

In [32]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [34]:
A.shape

(2, 2)

In [37]:
A.dtype

dtype('int64')

In [38]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [39]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [40]:
print(A)

[[1 2]
 [3 4]]


In [41]:
A * 10

array([[10, 20],
       [30, 40]])

In [42]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [43]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [44]:
X[0]

array([51, 55])

In [45]:
X[0][1]

np.int64(55)

In [46]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [49]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [50]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [52]:
X > 15

array([ True,  True, False,  True, False, False])

In [53]:
X[X > 15]

array([51, 55, 19])